adminUser: admin
adminPassword: admin

replicas: 1

persistence:
  enabled: true
  type: pvc
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  # existingClaim: ""

service:
  type: NodePort
  port: 80
  nodePort: 32000 # NodePort trong range 30000-32767

sidecar:
  dashboards:
    enabled: false
  datasources:
    enabled: false
